#ifndef __ASM_ARCH_IRQS_S1NTT_H__
#define __ASM_ARCH_IRQS_S1NTT_H__ __FILE__

#define IRQ_DET_35		IRQ_EINT6
#define IRQ_nINT_ONEDRAM_AP	IRQ_EINT11
#define IRQ_PHONE_ACTIVE	IRQ_EINT(19)
#define IRQ_BT_HOST_WAKE	IRQ_EINT(21)
#define IRQ_nSIM_DETECT		IRQ_EINT(27)	/* NC! */
#define IRQ_T_FLASH_DETECT	IRQ_EINT(28)
#define IRQ_EAR_SEND_END	IRQ_EINT(30)

#endif
