#
# Makefile for ST-Ericsson CG2900 connectivity multifunction miscellaneous devices
#
obj-$(CONFIG_MFD_CG2900)            += cg2900.o
cg2900-objs                         := cg2900_core.o cg2900_uart.o cg2900_char_devices.o cg2900_audio.o cg2900_chip.o stlc2690_chip.o
export-objs                         := cg2900_core.o

