/* Automatically generated by kernel/timeconst.pl */
/* Conversion constants for HZ == 256 */

#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 256
#error "kernel/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32        U64_C(0xfa000000)
#define HZ_TO_MSEC_ADJ32        U64_C(0x3e000000)
#define HZ_TO_MSEC_SHR32        30
#define HZ_TO_MSEC_NUM          U64_C(125)
#define HZ_TO_MSEC_DEN          U64_C(32)
#define MSEC_TO_HZ_MUL32        U64_C(0x83126e98)
#define MSEC_TO_HZ_ADJ32        U64_C(0x1fbe76c8b)
#define MSEC_TO_HZ_SHR32        33
#define MSEC_TO_HZ_NUM          U64_C(32)
#define MSEC_TO_HZ_DEN          U64_C(125)
#define HZ_TO_USEC_MUL32        U64_C(0xf4240000)
#define HZ_TO_USEC_ADJ32        U64_C(0xc0000)
#define HZ_TO_USEC_SHR32        20
#define HZ_TO_USEC_NUM          U64_C(15625)
#define HZ_TO_USEC_DEN          U64_C(4)
#define USEC_TO_HZ_MUL32        U64_C(0x8637bd06)
#define USEC_TO_HZ_ADJ32        U64_C(0x7ffde7210be)
#define USEC_TO_HZ_SHR32        43
#define USEC_TO_HZ_NUM          U64_C(4)
#define USEC_TO_HZ_DEN          U64_C(15625)

#endif /* KERNEL_TIMECONST_H */
