##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################


obj-$(CONFIG_ACCEL_KXSD9)	+= kxsd9_2042.o


obj-$(CONFIG_ACCEL_BMA020)	+= bma020_i2c.o \
                               bma020.o \
	                           bma020_acc.o

obj-$(CONFIG_ACCEL_SMB380)	+= smb_i2c.o \
                               smb380.o \
	                           smb_acc.o \
	                           smb380calib.o

obj-$(CONFIG_SENSORS_KR3D_ACCEL)	+= kr3dh_accel_driver.o

obj-$(CONFIG_ACCEL_BMA222)	+= bma222.o \
								bma222_i2c.o \
								 bma222_acc.o							
                        

