##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################



obj-$(CONFIG_OPTICAL_GP2A)			+= gp2a.o
obj-$(CONFIG_OPTICAL_TAOS_TRITON)	+= taos_triton.o
obj-$(CONFIG_OPTICAL_CAPELLA_TRITON)	+= capella_cm3663.o
				  
				  

